### POST user
POST http://localhost:3001/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

### POST user - Login 

POST http://localhost:3001/login
content-Type:application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}


### PUT - update password 

PUT http://localhost:3001/change-password
content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}

